#혼자서해보기(p 123)
library(ggplot2)
library(dplyr)
midwest <- as.data.frame(ggplot2::midwest)
head(midwest)
tail(midwest)
dim(midwest)
summary(midwest)
str(midwest)
new_midwest <- midwest
new_midwest <- rename(new_midwest, total = poptotal)
new_midwest <- rename(new_midwest, asian = popasian)
head(new_midwest,2)
new_midwest$total_asian <-(new_midwest$asian / new_midwest$total)*100
head(new_midwest,2)
hist(new_midwest$total_asian)
midw_avg <- mean(new_midwest$total_asian)
size <- ifelse(new_midwest$total_asian > 0.4872462 ,"large","small")
table(size)
qplot(size)