library(readxl)
wheel <- read_excel("wheel.xlsx")
head(wheel,5)


fan <- read_excel("fan.xlsx")
head(fan,5)
tail(fan,5)
metro <- read_excel("metro.xlsx")
head(metro,5)
summary(metro)
View(metro)
library(dplyr)
st_shin <- metro %>% filter(역명 == "신금호")
summary(st_shin)
st_wang <- metro %>% filter(역명 == "왕십리(성동구청)")
summary(st_wang)
head(st_wang)
st_wang %>% filter(승하차 == "승차") %>% select(날짜,구분, 역명, 승하차)
library(dplyr)
st_shindo <- metro %>% filter(역명 == "신도림")
head(st_shindo,10)
summary(st_shindo)
summary(st_wang)
